### ISSUE TITLE
Size limit on describeParameters 

### ISSUE THREAD

**Issue by brendangibat** [nak2k/node-ssm-params#5]
describeParameters accepts a batch size for the AWS API call, but there isn't an option to pass it through for queryParameterNamesWithPrefix. describeParameters fails if requesting more that 10 but not specifying a batch size, which is the default request limit size for the AWS API call (this can be raised through AWS support though).

Can you limit the batch size passed from getParameters to describeParameters? Alternatively you can set the batch size for describeParameters (there was no default for the AWS SDK version I was using), which your code will then correctly iterate over all the subsequent callbacks for the NextTarget (tested locally).

**Comment by nak2k** [comment]
Thank you for your interest in this package.

This problem was caused by incorrect usage of getParameters.

Since getParameters is called in parallel for many parameters, it works correctly with v0.0.4.

**Comment by brendangibat** [comment]
Thanks! I'm marking as completed.
