### ISSUE TITLE
Add hierarchy support

### ISSUE THREAD

**Issue by nak2k** [nak2k/node-ssm-params#6]
https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-ec2-systems-manager-adds-hierarchy-tagging-and-notification-support-for-parameter-store/

**Comment by OliverCole** [comment]
Does this mean turning names like `/foo/bar/baz` into `{foo: {bar: {baz: "hunter2"}}}`?

If so, 👍. It's the main thing this module doesn't do that my own code does!

**Comment by nak2k** [comment]
Thank you for your interest in this package.

I have published `ssm-params@0.0.6` that supports hierarchy parameters.

> Does this mean turning names like /foo/bar/baz into {foo: {bar: {baz: "hunter2"}}}?

Yes, it does.

I have added an example of that case, so please look at the above commit.
